# LaTeX2HTML 95.1 (Fri Jan 20 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{figure}vspace18cmlabelxsection{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img140.gif">'; 
$key = q/{displaymath}arrayllxi;;SPM_gt;;s,;SPM_amp;rm3D;couplingxi;;SPM_lt;;s,;SPM_amp;rm2D;couplingarray{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img37.gif">'; 
$key = q/{figure}%vspace7.5inlabelthetatemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img61.gif">'; 
$key = q/{displaymath}rmepsilon;equiv;H_c2,parallelhatcH_c2,perphatc;;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img47.gif">'; 
$key = q/{figure}vspace19cmlabelcsbixray{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img20.gif">'; 
$key = q/{displaymath}0.882xi_0ell{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img143.gif">'; 
$key = q/{table}[p]labelresistanis{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img134.gif">'; 
$key = q/{figure}vspace20cmlabelhydeffect{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img119.gif">'; 
$key = q/{table}labelstiitccentertabular||c|c|c||hline;SPM_amp;;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;MethodofPreparation;SPM_amp;Ref.;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;1.70;SPM_amp;KHg_inline$_2$_inline;SPM_amp;citekoike81;SPM_amp;;SPM_amp;1.82;SPM_amp;sequential;SPM_amp;citeiye83;SPM_amp;;SPM_amp;1.84;SPM_amp;sequential;SPM_amp;citeiye83;SPM_amp;;SPM_amp;1.848;SPM_amp;KHg_inline$_2$_inline;SPM_amp;citedelong82a;SPM_amp;;SPM_amp;1.870;SPM_amp;sequential;SPM_amp;citedelong82a;SPM_amp;;SPM_amp;1.896;SPM_amp;KHg_inline$_2$_inline;SPM_amp;presentwork;SPM_amp;;SPM_amp;1.90;SPM_amp;KHg_inline$_2$_inline;SPM_amp;citekoike81;SPM_amp;;SPM_amp;1.90;SPM_amp;sequential;SPM_amp;citevogel81;SPM_amp;;SPM_amp;1.90;SPM_amp;sequential;SPM_amp;citeprys81;SPM_amp;;SPM_amp;1.90;SPM_amp;KHg_inline$_2$_inline;SPM_amp;citetanuma81;SPM_amp;;SPM_amp;1.93;SPM_amp;sequential;SPM_amp;citealexander81;SPM_amp;;SPM_amp;1.94;SPM_amp;KHg_inline$_2$_inline;SPM_amp;citetanuma81;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img16.gif">'; 
$key = q/{figure}vspace20cmlabelhydxrd{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img19.gif">'; 
$key = q/{table}labelkappatablecentertabular|l|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Sampleorigin;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;_inline$rmH_c2,perphatc(0)$_inline(g);SPM_amp;_inline$rmH_c2,parallelhatc(0)$_inline(g);SPM_amp;_inline$rmkappa_parallelhatc(0)$_inline;SPM_amp;_inline$rmkappa_perphatc(0)$_inline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlineMIT;SPM_amp;1.53;SPM_amp;749;SPM_amp;89;SPM_amp;0.56;SPM_amp;4.7;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;MIT;SPM_amp;1.54;SPM_amp;748;SPM_amp;86;SPM_amp;0.54;SPM_amp;4.7;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;MIT;SPM_amp;0.95;SPM_amp;407;SPM_amp;46;SPM_amp;0.70;SPM_amp;5.6;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Ref.~citeiye82;SPM_amp;0.72;SPM_amp;715;SPM_amp;62.4;SPM_amp;0.81;SPM_amp;9.3;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Ref.~citeiye82;SPM_amp;0.86;SPM_amp;654;SPM_amp;49.2;SPM_amp;0.64;SPM_amp;8.5;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Ref.~citeiye82;SPM_amp;0.73;SPM_amp;575;SPM_amp;58.8;SPM_amp;0.77;SPM_amp;7.5;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img58.gif">'; 
$key = q/{displaymath}rm1epsilon;=;left[dH_c2,parallelhatcdTright]left[dH_c2,perphatcdTright]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img83.gif">'; 
$key = q/{figure}vspace4.5inlabelninety-tangent{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img55.gif">'; 
$key = q/{figure}vspace16cmlabelkhdos{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img114.gif">'; 
$key = q/{figure}vspace7inlabelalloychoice{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img15.gif">'; 
$key = q/{figure}setlengthunitlength0.0125inpicture(325,395)(169,350)thicklinesput(340,662)circle16put(340,662)circle6put(340,622)circle6put(340,622)circle16put(340,582)circle16put(340,582)circle6put(340,542)circle6put(340,542)circle16put(340,502)circle16put(340,502)circle6put(340,462)circle6put(340,462)circle16put(340,422)circle16put(340,422)circle6put(177,662)circle16put(171,668)line(1,-1)12put(183,668)line(-1,-1)12put(177,622)circle16put(183,628)line(-1,-1)12put(171,628)line(1,-1)12put(177,582)circle16put(171,588)line(1,-1)12put(183,588)line(-1,-1)12put(177,542)circle16put(183,548)line(-1,-1)12put(171,548)line(1,-1)12put(177,502)circle16put(171,508)line(1,-1)12put(183,508)line(-1,-1)12put(177,462)circle16put(183,468)line(-1,-1)12put(171,468)line(1,-1)12put(177,422)circle16put(171,428)line(1,-1)12put(183,428)line(-1,-1)12put(177,382)circle16put(183,388)line(-1,-1)12put(171,388)line(1,-1)12put(340,382)circle6put(340,382)circle16multiput(260,680)(0.00000,8.00000)8line(0,1)4.000put(260,740)vector(0,1)0multiput(360,520)(8.00000,0.00000)8line(1,0)4.000put(420,520)vector(1,0)0multiput(280,400)(8.20513,0.00000)20line(1,0)4.103multiput(280,640)(8.20513,0.00000)20line(1,0)4.103put(240,400)framebox(40,240)put(320,680)line(0,-1)320put(200,680)line(0,-1)320put(280,720)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twltt_inline$rmH_mod$_inlineput(440,510)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlttc-axisput(440,535)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlttGraphiteput(450,400)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlttz=0put(450,640)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlttz=Lpicturelabelscingfract{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img42.gif">'; 
$key = q/{figure}vspace12cmlabelassltemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img9.gif">'; 
$key = q/{figure}vspace20cmlabelstitransdata{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img122.gif">'; 
$key = q/{figure}vspace20cmlabelstixr{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img18.gif">'; 
$key = q/{figure}vspace12cmlabelhitctheta{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img12.gif">'; 
$key = q/{displaymath}rmrho_a(4.2K),approx,rho_c(4.2K)fracrho_a(100K)rho_c(100K);.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img145.gif">'; 
$key = q/{displaymath}rmell;=;frac4pihbarI_c3e^2rho_ak_F;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img148.gif">'; 
$key = q/{figure}vspace5inlabelproxeff{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img93.gif">'; 
$key = q/{figure}vspace16cm%labelnbse2fit{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img104.gif">'; 
$key = q/{figure}vspace17cmlabelkhC_v{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img112.gif">'; 
$key = q/{figure}vspace15cmlabeltase2resist{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img116.gif">'; 
$key = q/{figure}vspace5inlabelhcfig{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img66.gif">'; 
$key = q/{displaymath}kappa,propto,frac11+t^2{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img59.gif">'; 
$key = q/{figure}vspace4.5inlabelmospread{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img54.gif">'; 
$key = q/{displaymath}rmlambda_tr;=;0.72fracrho_ak_FT_cI_c{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img149.gif">'; 
$key = q/{figure}vspace18cmlabeltmdcHfig{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img115.gif">'; 
$key = q/{figure}vspace5in%labelentelfit{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img105.gif">'; 
$key = q/{displaymath}rmV_cyl;=;frac2piI_ccalA_max^e{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img131.gif">'; 
$key = q/{figure}vspace18cmlabelTaN{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img60.gif">'; 
$key = q/{figure}vspace15cmlabelsoftmode{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img135.gif">'; 
$key = q/{figure}vspace5inlabelholzfs{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img106.gif">'; 
$key = q/{displaymath}rmH_c2,perphatc;=;frac2sqrt6H_clambda_parallelhatcd{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img70.gif">'; 
$key = q/{figure}vspace19cmlabelrhofig{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img29.gif">'; 
$key = q/{figure}vspace15cmlabelinclusion{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img124.gif">'; 
$key = q/{figure}setlengthunitlength0.0125inpicture(520,455)(120,330)thicklinesput(20,580)circle0put(40,680)circle14put(38,360)circle14put(460,640)circle14put(460,400)circle14put(160,642)circle6put(160,642)circle16put(162,482)circle16put(317,642)circle16put(320,482)circle16put(320,482)circle6put(510,400)vector(0,-1)60put(510,640)vector(0,1)60put(180,750)vector(-1,0)0put(180,750)vector(1,0)120put(480,340)line(1,0)60put(480,700)line(1,0)60put(300,780)line(0,-1)60put(180,780)line(0,-1)60put(140,540)framebox(200,120)put(140,380)framebox(200,120)put(180,340)framebox(120,360)put(340,560)line(1,0)40put(380,560)line(0,-1)80put(380,480)line(-1,0)40put(340,480)line(0,1)1put(340,400)line(1,0)120put(340,640)line(1,0)120put(180,680)line(-1,0)140put(180,360)line(-1,0)140put(156,488)line(1,-1)12put(168,488)line(-1,-1)12put(323,648)line(-1,-1)12put(311,648)line(1,-1)12put(500,600)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrm30mmput(25,545)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmPrimaryput(30,520)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmCoilput(440,545)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmSecondaryput(450,520)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmCoilput(220,765)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrm4.0mmput(205,725)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrminnerdiameterpicturelabelibridge{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img39.gif">'; 
$key = q/{figure}vspace8inlabelphasediag{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img14.gif">'; 
$key = q/{displaymath}rmpsi(x);equiv;fracddxlnGamma(x);.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img78.gif">'; 
$key = q/{figure}vspace6.5inlabelklbfig{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img89.gif">'; 
$key = q/{figure}vspace5.5inlabelsumtemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img82.gif">'; 
$key = q/{table}labelresidsumcentertabular|l|cccccc|hline_inline$rmT_c$_inline;SPM_amp;t_inline$rmequivTT_c$_inline;SPM_amp;FitType;SPM_amp;_inline$calR$_inline;SPM_amp;_inline$rmH_c2(0^circ)$_inline(g);SPM_amp;1_inline$epsilon$_inline;SPM_amp;_inline$rmH_c$_inline(g)hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.76;SPM_amp;AGL;SPM_amp;1.43;SPM_amp;23.1;SPM_amp;4.5;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.76;SPM_amp;AGL;SPM_amp;1.11;SPM_amp;14.5;SPM_amp;12.5;SPM_amp;24.5;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.76;SPM_amp;TF;SPM_amp;1.06;SPM_amp;17.5;SPM_amp;8.2;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.76;SPM_amp;TF;SPM_amp;0.58;SPM_amp;14.8;SPM_amp;12;SPM_amp;24;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.55;SPM_amp;AGL;SPM_amp;1.24;SPM_amp;33;SPM_amp;5.5;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.55;SPM_amp;AGL;SPM_amp;0.84;SPM_amp;19;SPM_amp;15.5;SPM_amp;43;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.55;SPM_amp;TF;SPM_amp;0.75;SPM_amp;33;SPM_amp;7;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.55;SPM_amp;TF;SPM_amp;0.47;SPM_amp;23;SPM_amp;13;SPM_amp;41;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.29;SPM_amp;AGL;SPM_amp;1.18;SPM_amp;47;SPM_amp;9.5;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.29;SPM_amp;AGL;SPM_amp;0.39;SPM_amp;35;SPM_amp;14;SPM_amp;65;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.29;SPM_amp;TF;SPM_amp;0.83;SPM_amp;50;SPM_amp;9.5;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;0.29;SPM_amp;TF;SPM_amp;0.26;SPM_amp;35.8;SPM_amp;16;SPM_amp;65;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinehline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.95;SPM_amp;0.45;SPM_amp;AGL;SPM_amp;0.24;SPM_amp;24;SPM_amp;10;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinehline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.73citeiye82;SPM_amp;0.55;SPM_amp;AGL;SPM_amp;0.08;SPM_amp;26;SPM_amp;11.3;SPM_amp;0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img68.gif">'; 
$key = q/{figure}centervskip9.cmlabelcsbistruct{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img132.gif">'; 
$key = q/{figure}%vspace7.5inlabelhctemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img63.gif">'; 
$key = q/{}dag{}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img91.gif">'; 
$key = q/{figure}vspace20cmlabelstitcvsP{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img120.gif">'; 
$key = q/{figure}vspace12cmlabeltcdef{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img31.gif">'; 
$key = q/{figure}vspace7.5inlabelinhomo{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img100.gif">'; 
$key = q/{table}centervspace0.5inlabelkhtctabletabular|cccc|hline;SPM_amp;;SPM_amp;;SPM_amp;Compound(stage);SPM_amp;MethodofPreparation;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;Ref.;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KH_23$_inline(II);SPM_amp;chemisorption;SPM_amp;_inline$;SPM_lt;$_inline0.052;SPM_amp;citesano80;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_4KH_x$_inline(I);SPM_amp;KHpowder;SPM_amp;_inline$;SPM_lt;$_inline0.070;SPM_amp;citesuzuki85b;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8K$_inline(I);SPM_amp;NA;SPM_amp;0.150;SPM_amp;citekoike80;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KH_0.19$_inline(53%I+47%II);SPM_amp;chemisorption;SPM_amp;0.22;SPM_amp;citekaneiwa82;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KH_x$_inline+_inline$rmC_24K$_inline(II);SPM_amp;KHpowder;SPM_amp;0.31;SPM_amp;citesuzuki85b;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img111.gif">'; 
$key = q/{displaymath}rmointdvecq:N(vecq):v_perpvecH(vecq){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img101.gif">'; 
$key = q/{figure}vspace15cmlabeltranshape{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img65.gif">'; 
$key = q/{table}centervspace0.5inlabelkhcvtabletabular|c|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Compound;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;_inline$Theta_D$_inline(K);SPM_amp;_inline$rmT_E$_inline(K);SPM_amp;N(0)(stateseV_inline$cdot$_inlineC-atom);SPM_amp;_inline$rmlambda_ep$_inline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8K$_inline;SPM_amp;0.15;SPM_amp;393.5;SPM_amp;82.2;SPM_amp;0.31;SPM_amp;0.30;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8Rb$_inline;SPM_amp;0.026;SPM_amp;245.4;SPM_amp;60.3;SPM_amp;0.28;SPM_amp;0.27;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KH_0.05$_inline;SPM_amp;0.19_inline$^dagger$_inline;SPM_amp;403;SPM_amp;90.7;SPM_amp;0.29;SPM_amp;0.31;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8RbH_0.05$_inline;SPM_amp;?;SPM_amp;319.1;SPM_amp;56.2;SPM_amp;?;SPM_amp;?;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KH_0.65$_inline;SPM_amp;_inline$;SPM_lt;$_inline0.05;SPM_amp;350;SPM_amp;58.1;SPM_amp;0.10;SPM_amp;0.87;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img113.gif">'; 
$key = q/{figure}vspace7.5inlabelramfig{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img21.gif">'; 
$key = q/{figure}vspace7.5inlabelhparvst{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img76.gif">'; 
$key = q/{table}centervspace0.5inlabelhydtctabletabular|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Initial_inline$rmT_c$_inline(K);SPM_amp;Initial_inline$DeltaT_c$_inline_inline$rmT_c$_inline;SPM_amp;Initialcolor;SPM_amp;Final_inline$rmT_c$_inline(K);SPM_amp;Final_inline$rmDeltaT_c$_inline_inline$rmT_c$_inline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.719;SPM_amp;0.20;SPM_amp;gold;SPM_amp;0.941;SPM_amp;0.21%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.875;SPM_amp;7.3_inline$times10^-2$_inline;SPM_amp;gold;SPM_amp;1.519;SPM_amp;1.2_inline$times10^-2$_inline%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.875;SPM_amp;7.3_inline$times10^-2$_inline;SPM_amp;gold;SPM_amp;1.535_inline$^S$_inline;SPM_amp;7.8_inline$times10-3$_inline%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.317;SPM_amp;0.14;SPM_amp;copper;SPM_amp;1.497;SPM_amp;6.5_inline$times10^-2$_inline%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.472_inline$^ast$_inline;SPM_amp;3.0_inline$times10^-2$_inline;SPM_amp;copper;SPM_amp;1.562;SPM_amp;2.4_inline$times10^-2$_inline%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.497_inline$^dagger$_inline;SPM_amp;6.5_inline$times10^-2$_inline;SPM_amp;violet_inline$^dagger$_inline;SPM_amp;1.491;SPM_amp;6.2_inline$times10^-2$_inline%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.528;SPM_amp;4.7_inline$times10^-2$_inline;SPM_amp;pink;SPM_amp;1.515;SPM_amp;2.2_inline$times10^-2$_inline%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.879;SPM_amp;8.5_inline$times10^-2$_inline;SPM_amp;blue;SPM_amp;_inline$;SPM_lt;$_inline1.2;SPM_amp;NA%;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img118.gif">'; 
$key = q/{figure}vspace12cm%labelzeedef{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img25.gif">'; 
$key = q/{figure}vspace15cmlabelassltheta{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img10.gif">'; 
$key = q/{displaymath}rmT_D;=;frachbarpik_Btau_col{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img128.gif">'; 
$key = q/{table}labelklbgicscentertabular|c|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Compound;SPM_amp;_inline$r$_inline;SPM_amp;1_inline$epsilon$_inline;SPM_amp;_inline$xi_parallelhatc(0)$_inline;SPM_amp;_inline$rmI_c$_inline(AA);SPM_amp;Ref.;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KHg$_inline;SPM_amp;64-76;SPM_amp;30-31;SPM_amp;52;SPM_amp;13.6;SPM_amp;citekoike81,tanuma81;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KHg$_inline;SPM_amp;91;SPM_amp;25;SPM_amp;57;SPM_amp;13.56;SPM_amp;citeprys83;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8RbHg$_inline;SPM_amp;86-176;SPM_amp;20-41;SPM_amp;58-83;SPM_amp;13.56;SPM_amp;citeiye82;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_4KTl_1.5$_inline;SPM_amp;514;SPM_amp;5;SPM_amp;57;SPM_amp;12.1;SPM_amp;citeprys83,vogel81;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_4KHg$_inline;SPM_amp;2000;SPM_amp;6-16;SPM_amp;200-300;SPM_amp;10.24;SPM_amp;thiswork;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_4KHg$_inline;SPM_amp;2000-2800_inline$^dagger$_inline;SPM_amp;10-11;SPM_amp;200-240;SPM_amp;10.24;SPM_amp;citeiye83;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_4RbHg$_inline;SPM_amp;3000-4500_inline$^dagger$_inline;SPM_amp;10;SPM_amp;261-320;SPM_amp;10.76;SPM_amp;citeiye82;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8K$_inline;SPM_amp;6.7e5;SPM_amp;4.7-6.2;SPM_amp;1500-2900;SPM_amp;5.4;SPM_amp;citekoike81,koike80;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img92.gif">'; 
$key = q/{displaymath}sigma^2;=;sum_irm(H_i^exp,-,H_i^theor)^2nu{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img74.gif">'; 
$key = q/{displaymath}rmT_c;=;fracTheta_D1.45:exp-left[frac1.04left(1,+,lambda_epright)lambda_ep;-;mu^*left(1;+;0.62lambda_epright)right]{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img96.gif">'; 
$key = q/{figure}vspace15cmlabelfquant{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img139.gif">'; 
$key = q/{table}centerlabelhitctabletabular|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Compound;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;1_inline$epsilon$_inline;SPM_amp;_inline$xi(0)$_inline(AA);SPM_amp;Ref.;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline%La_inline$_2-x$_inlineSr_inline$_x$_inlineCuO_inline$_4-y$_inline;SPM_amp;38.1;SPM_amp;NR;SPM_amp;13;SPM_amp;citeorlando87bLa_inline$_1.92$_inlineSr_inline$_0.08$_inlineCuO_inline$_4-y$_inline_inline$^dagger$_inline;SPM_amp;20;SPM_amp;5;SPM_amp;37(_inline$rmperphatc$_inline);7(_inline$rmparallelhatc$_inline);SPM_amp;citeiye88La_inline$_2-x$_inlineSr_inline$_x$_inlineCuO_inline$_4-y$_inline;SPM_amp;_inline$approx$_inline30;SPM_amp;13;SPM_amp;NR;SPM_amp;citeuchida87La_inline$_2-x$_inlineSr_inline$_x$_inlineCuO_inline$_4-y$_inline;SPM_amp;36;SPM_amp;4-5;SPM_amp;26.6;SPM_amp;citevanbentum87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline;SPM_amp;81-90;SPM_amp;20;SPM_amp;NR;SPM_amp;citemcguire87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline;SPM_amp;91.4;SPM_amp;_inline$;SPM_lt;$_inline12;SPM_amp;14.1;SPM_amp;citeorlando87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline;SPM_amp;_inline$approx$_inline90;SPM_amp;NR;SPM_amp;15.2;SPM_amp;citerettori87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline;SPM_amp;89.5;SPM_amp;NR;SPM_amp;17;SPM_amp;citeorlando87aYBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;88.8;SPM_amp;10;SPM_amp;NR;SPM_amp;citedinger87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline;SPM_amp;92;SPM_amp;4-5;SPM_amp;12.6;SPM_amp;citevanbentum87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;88.8;SPM_amp;4.8;SPM_amp;34(_inline$rmperphatc$_inline);7(_inline$rmparallelhatc$_inline);SPM_amp;citeworthington87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline;SPM_amp;93;SPM_amp;25-50;SPM_amp;NR;SPM_amp;citewelch87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;89.7;SPM_amp;3.6;SPM_amp;23(_inline$rmperphatc$_inline);6.3(_inline$rmparallelhatc$_inline);SPM_amp;citemoodera88YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;91;SPM_amp;2(90K);5(86.5K);SPM_amp;33.9(_inline$rmperphatc$_inline);10(_inline$rmparallelhatc$_inline);SPM_amp;citeiye87YBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;94;SPM_amp;6;SPM_amp;22(_inline$rmperphatc$_inline);6(_inline$rmparallelhatc$_inline);SPM_amp;citesakakibara87HoBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;88.1;SPM_amp;3-7;SPM_amp;22-24(_inline$rmperphatc$_inline);6-7(_inline$rmparallelhatc$_inline);SPM_amp;citeiye87aBi_inline$_2$_inlineSr_inline$_2$_inlineCaCu_inline$_2$_inlineO_inline$_(8+x)$_inline_inline$^dagger$_inline;SPM_amp;80;SPM_amp;6;SPM_amp;30-40(_inline$rmperphatc$_inline);1-3(_inline$rmparallelhatc$_inline);SPM_amp;citeiye88%TmBa_inline$_2$_inlineCu_inline$_3$_inlineO_inline$_(7-y)$_inline_inline$^dagger$_inline;SPM_amp;86;SPM_amp;8;SPM_amp;NR;SPM_amp;citenoel87hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img13.gif">'; 
$key = q/{figure}vspace5in%labelbutlerellipse{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img103.gif">'; 
$key = q/{displaymath}rmh^*;=;H_c2left(left.fracdH_c2dTright|_T_cT_cright){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img81.gif">'; 
$key = q/{table}labellambdatablecentertabular|c|ccc|hline;SPM_amp;;SPM_amp;;SPM_amp;Compound;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;_inline$rmTheta_D$_inline(K);SPM_amp;_inline$lambda_ep$_inline;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_4KHg$_inline;SPM_amp;0.73citeiye82;SPM_amp;269citealexander81;SPM_amp;0.38citeiye82;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8RbHg$_inline;SPM_amp;1.44citealexander81;SPM_amp;235citealexander81;SPM_amp;0.44citeiye82,alexander81;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmC_8KHg$_inline;SPM_amp;1.93citealexander81;SPM_amp;260citealexander81,301citealexander80;SPM_amp;0.46citetanuma81,alexander80;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img98.gif">'; 
$key = q/{figure}vspace7.5inlabelhc2theta{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img45.gif">'; 
$key = q/{figure}vspace12cmlabelnesting{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img121.gif">'; 
$key = q/{table}labelneutnumcentertabular|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Type;SPM_amp;_inline$rmI_c$_inline(AA);SPM_amp;_inline$rmN_Hg$_inline;SPM_amp;_inline$rmz_K$_inline(AA);SPM_amp;_inline$Delta$_inlinez(AA);SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;gold,majority;SPM_amp;10.24;SPM_amp;1.09;SPM_amp;1.997;SPM_amp;0.184;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;pink,majority;SPM_amp;10.24;SPM_amp;0.96;SPM_amp;2.287;SPM_amp;0.0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hydrogenated,majority;SPM_amp;10.24;SPM_amp;1.3;SPM_amp;2.4;SPM_amp;0.24;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;majorityciteyang84;SPM_amp;10.24;SPM_amp;1.0;SPM_amp;2.1;SPM_amp;0.0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;minorityciteyang84;SPM_amp;10.83;SPM_amp;1.3;SPM_amp;2.8;SPM_amp;0.0;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;majorityciteelmakrini80;SPM_amp;10.16;SPM_amp;1.0;SPM_amp;2.34;SPM_amp;0.25;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img27.gif">'; 
$key = q/{table}labellinearparamscentertabular|c|ccccc|hlineExp._inline$rmT_c$_inline(K);SPM_amp;_inline$perp$_inlineor_inline$parallel$_inline;SPM_amp;_inline$rmH_c2(0)$_inline(g);SPM_amp;Fit_inline$rmT_c$_inline(K);SPM_amp;_inline$rmleft|dH_c2dTright|$_inline(gK);SPM_amp;calR_inline$times$_inline100hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.72citeiye82;SPM_amp;_inline$perp$_inline;SPM_amp;715;SPM_amp;NR;SPM_amp;993;SPM_amp;NR;SPM_amp;_inline$parallel$_inline;SPM_amp;62.4;SPM_amp;NR;SPM_amp;86.7;SPM_amp;NR;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.73citeiye82;SPM_amp;_inline$perp$_inline;SPM_amp;570;SPM_amp;0.73;SPM_amp;786;SPM_amp;4.4;SPM_amp;_inline$parallel$_inline;SPM_amp;58.5;SPM_amp;0.73;SPM_amp;80.3;SPM_amp;0.01;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.86citeiye82;SPM_amp;_inline$perp$_inline;SPM_amp;654;SPM_amp;NR;SPM_amp;760.5;SPM_amp;NR;SPM_amp;_inline$parallel$_inline;SPM_amp;49.2;SPM_amp;NR;SPM_amp;57.2;SPM_amp;NR;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;0.95;SPM_amp;_inline$perp$_inline;SPM_amp;407;SPM_amp;1.09;SPM_amp;374;SPM_amp;0.79;SPM_amp;_inline$parallel$_inline;SPM_amp;45.9;SPM_amp;1.04;SPM_amp;44.0;SPM_amp;0.13;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.53;SPM_amp;_inline$perp$_inline;SPM_amp;749;SPM_amp;1.53;SPM_amp;488;SPM_amp;7.88;SPM_amp;_inline$parallel$_inline;SPM_amp;89.7;SPM_amp;1.65;SPM_amp;54.4;SPM_amp;0.63;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;1.54;SPM_amp;_inline$perp$_inline;SPM_amp;748;SPM_amp;1.52;SPM_amp;493;SPM_amp;0.69;SPM_amp;_inline$parallel$_inline;SPM_amp;85.8;SPM_amp;1.62;SPM_amp;53.0;SPM_amp;0.16;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img75.gif">'; 
$key = q/{displaymath}arrayllell,gg,xi,;SPM_amp;rmclean;limitell,ll,xi,;SPM_amp;rmdirty;limitarray;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img36.gif">'; 
$key = q/{figure}vspace5inlabelepstemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img85.gif">'; 
$key = q/{figure}vspace10cm%labelKhc2theta{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img56.gif">'; 
$key = q/{figure}%vspace6inlabelmisalign{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img51.gif">'; 
$key = q/{figure}vspace14cm%labelfig:meiss{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img33.gif">'; 
$key = q/{figure}vspace16cmlabelc6k{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img107.gif">'; 
$key = q/{figure}vspace5.5inlabelrbhct{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img87.gif">'; 
$key = q/{figure}vspace16cmlabelwhhfit{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img79.gif">'; 
$key = q/{displaymath}arraylllambda,;SPM_lt;,xi,;SPM_amp;rmtype;Ilambda,;SPM_gt;,xi,;SPM_amp;rmtype;IIarray;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img35.gif">'; 
$key = q/{figure}%vspace15cmlabelcsbi:alloytc{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img125.gif">'; 
$key = q/{figure}vspace4.5inlabeltilteffect{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img52.gif">'; 
$key = q/{displaymath}rmxi_0equiv0.18hbarv_Fk_BT_c{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img144.gif">'; 
$key = q/{displaymath}rmn;=;frac4k_F^23piI_c{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img147.gif">'; 
$key = q/{table}labelstitccentertabular||c|c|c|c|c|c||hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;T_inline$rm_prep$_inline;SPM_amp;_inline$Delta$_inlineT;SPM_amp;Time;SPM_amp;Color;SPM_amp;Ref.;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$;SPM_lt;$_inline1.5;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0?;SPM_amp;oneweek;SPM_amp;copper;SPM_amp;citekoike81_inline$;SPM_lt;$_inline0.8;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0?;SPM_amp;?;SPM_amp;copper;SPM_amp;citealexander810.719_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0;SPM_amp;twoweeks;SPM_amp;gold;SPM_amp;presentwork%0.72;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0?;SPM_amp;severaldays;SPM_amp;copper-pink;SPM_amp;citeiye820.726;SPM_amp;200_inline$^circ$_inline;SPM_amp;6_inline$^circ$_inline;SPM_amp;twoweeks;SPM_amp;gold;SPM_amp;presentwork%0.73;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0?;SPM_amp;severaldays;SPM_amp;copper-pink;SPM_amp;citeiye820.822_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0;SPM_amp;twoweeks;SPM_amp;gold;SPM_amp;presentwork%0.86;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0?;SPM_amp;severaldays;SPM_amp;copper-pink;SPM_amp;citeiye820.875_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;10_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;gold;SPM_amp;presentwork%0.949_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;6_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;gold;SPM_amp;presentwork%1.09;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;10_inline$^circ$_inlineC;SPM_amp;?;SPM_amp;gold;SPM_amp;citeJ1401.198;SPM_amp;234_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;copper;SPM_amp;presentwork%1.317_inline$^dagger$_inline;SPM_amp;260_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;copper;SPM_amp;presentwork%1.36_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC_inline$^ddagger$_inline;SPM_amp;0_inline$^circ$_inlineC?;SPM_amp;twoweeks;SPM_amp;?;SPM_amp;citedelong821.459;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;pink;SPM_amp;FromTimp.%1.46_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;yellowpink;SPM_amp;presentwork%1.472_inline$^dagger$_inline;SPM_amp;260_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;copper;SPM_amp;presentwork%1.508_inline$^dagger$_inline;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;twoweeks;SPM_amp;yellowpink;SPM_amp;presentwork%1.526;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inline;SPM_amp;twoweeks;SPM_amp;pink;SPM_amp;presentwork%1.528;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;threeweeks;SPM_amp;pink;SPM_amp;presentwork%1.536;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;threeweeks;SPM_amp;pink;SPM_amp;presentwork%1.539;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;threeweeks;SPM_amp;pink;SPM_amp;presentwork%1.56;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;0_inline$^circ$_inlineC;SPM_amp;14days;SPM_amp;pink;SPM_amp;citeJ140,timp831.65;SPM_amp;200_inline$^circ$_inlineC;SPM_amp;5_inline$^circ$_inlineC;SPM_amp;14days;SPM_amp;red;SPM_amp;citeJ140,timp83;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img17.gif">'; 
$key = q/{figure}vspace15cmlabelc8kstruct{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img1.gif">'; 
$key = q/{figure}vspace5inlabelTINKvsAGL{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img69.gif">'; 
$key = q/{displaymath}rmH_c2(0):approx:0.7left.fracdH_c2dTright|_T_cT_c;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img80.gif">'; 
$key = q/{figure}vspace12cmlabelnbgetemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img8.gif">'; 
$key = q/{displaymath}rmE;approx;momega^2langlex^2rangle;approx;frachbarmomega{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img136.gif">'; 
$key = q/{figure}vspace20cmlabel6bneut{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img23.gif">'; 
$key = q/{figure}centervskip9.cmlabelsdh:calc{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img129.gif">'; 
$key = q/{table}labeltcfreqcentertabular|ccc|hline;SPM_amp;;SPM_amp;_inline$rmT_c$_inline(K);SPM_amp;_inline$rmDeltaT_cT_c$_inline;SPM_amp;color;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;0.719;SPM_amp;0.20;SPM_amp;gold%;SPM_amp;;SPM_amp;0.726;SPM_amp;0.20;SPM_amp;gold%;SPM_amp;;SPM_amp;0.822;SPM_amp;0.17;SPM_amp;gold%;SPM_amp;;SPM_amp;0.875;SPM_amp;0.073;SPM_amp;gold%;SPM_amp;;SPM_amp;0.949;SPM_amp;0.20;SPM_amp;gold%;SPM_amp;;SPM_amp;1.198;SPM_amp;0.21;SPM_amp;copper%;SPM_amp;;SPM_amp;1.317;SPM_amp;0.138;SPM_amp;pink%;SPM_amp;;SPM_amp;1.443;SPM_amp;0.075;SPM_amp;pink;fromTimp%;SPM_amp;;SPM_amp;1.46;SPM_amp;0.096;SPM_amp;pink%;SPM_amp;;SPM_amp;1.472;SPM_amp;0.03;SPM_amp;pink%;SPM_amp;;SPM_amp;1.508;SPM_amp;0.1;SPM_amp;pink%;SPM_amp;;SPM_amp;1.526;SPM_amp;0.042;SPM_amp;pink%;SPM_amp;;SPM_amp;1.528;SPM_amp;0.047;SPM_amp;pink%;SPM_amp;;SPM_amp;1.536;SPM_amp;0.04;SPM_amp;pink%;SPM_amp;;SPM_amp;1.539;SPM_amp;0.02;SPM_amp;pink%;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img32.gif">'; 
$key = q/{figure}vspace8inlabeltranswidth{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img44.gif">'; 
$key = q/{figure}vspace8in%labelperpexplain{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img102.gif">'; 
$key = q/{figure}vspace15cmlabelassltc{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img11.gif">'; 
$key = q/{displaymath}rmT_c;=;Theta_Dexpleft(-frac1N(0)Vright){displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img109.gif">'; 
$key = q/{figure}vspace20cmlabel14cneut{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img22.gif">'; 
$key = q/{displaymath}rmsigma_i;=;H_c2,i^exp;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img73.gif">'; 
$key = q/{displaymath}rmell_a,=,hbark_Fne^2rho_a;.{displaymath}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img146.gif">'; 
$key = q/{figure}setlengthunitlength0.0125inpicture(535,415)(125,310)thicklinesput(520,642)oval(30,30)put(40,640)oval(30,30)put(200,480)line(0,1)200put(200,680)line(-1,0)80put(175,480)line(1,0)25put(120,480)line(1,0)25put(120,600)line(0,-1)120put(465,665)framebox(30,30)put(145,465)framebox(30,30)put(520,600)line(0,-1)105put(520,495)line(-1,0)40put(120,625)line(0,-1)25put(120,600)line(-1,0)80put(40,600)line(0,1)25put(40,655)line(0,1)25put(40,680)line(1,0)80put(120,680)line(0,-1)20put(360,440)line(0,-1)40put(380,440)line(0,-1)40put(320,320)framebox(160,80)put(360,670)line(0,1)10put(360,680)line(-1,0)20put(340,680)line(0,-1)160put(360,610)line(0,-1)90put(360,650)line(0,-1)20put(480,465)line(1,0)80put(560,465)line(0,1)215put(560,680)line(-1,0)40put(520,625)line(0,-1)25put(520,600)line(-1,0)120put(400,600)line(0,1)10put(495,680)line(1,0)25put(520,680)line(0,-1)20put(400,670)line(0,1)10put(400,680)line(1,0)65put(320,440)framebox(160,80)put(115,625)framebox(10,35)put(80,560)dashbox4(360,160)put(385,680)line(0,-1)80put(375,680)line(0,-1)80put(395,610)framebox(10,60)put(355,610)framebox(10,20)put(355,650)framebox(10,20)put(460,705)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmAmmeterput(135,450)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmVoltmeterput(320,690)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmInductanceBridgeput(135,640)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmGeThermometerput(345,480)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmLockInAmplifierput(340,445)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmOutputput(340,360)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmFlatbedPlormerput(490,480)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmReferenceput(335,510)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmSignalInputput(475,675)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmAput(510,635)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmOsc.put(35,640)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmIput(175,700)makebox(0,0)[lb]raisebox0pt[0pt][0pt]twlrmCryostatpicturelabelschematic{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img40.gif">'; 
$key = q/{figure}vspace5inlabelfig:holder{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img38.gif">'; 
$key = q/{figure}vspace5inlabelstiiepstemp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img86.gif">'; 
$key = q/{table}labelstoichtabcentertabular|c|ccccc|hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;Compound;SPM_amp;CKratio;SPM_amp;HgKratio;SPM_amp;Experiment;SPM_amp;Ref.;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hline;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;gold;SPM_amp;ND;SPM_amp;_inline$(1.09pm0.07)$_inline;SPM_amp;diffraction;SPM_amp;thiswork;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;pink;SPM_amp;ND;SPM_amp;_inline$(0.96pm0.03)$_inline;SPM_amp;diffraction;SPM_amp;thiswork;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;majority;SPM_amp;NR;SPM_amp;1.0;SPM_amp;diffraction;SPM_amp;citeyang84;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;minority;SPM_amp;NR;SPM_amp;1.3;SPM_amp;diffraction;SPM_amp;citeyang84;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;majority;SPM_amp;1.0;SPM_amp;1.0;SPM_amp;diffraction;SPM_amp;citeelmakrini80;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;majority;SPM_amp;(_inline$3.0pm1.5$_inline);SPM_amp;(_inline$0.77pm0.08$_inline);SPM_amp;RBS;SPM_amp;citeS175;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmT_c$_inline=0.73K;SPM_amp;4.74;SPM_amp;1.2;SPM_amp;chem.anal.;SPM_amp;thiswork;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmT_c$_inline=1.3K;SPM_amp;3.33;SPM_amp;0.8;SPM_amp;chem.anal.;SPM_amp;thiswork;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;_inline$rmT_c$_inline=1.54;SPM_amp;4.3;SPM_amp;1.05;SPM_amp;chem.anal.;SPM_amp;thiswork;SPM_amp;;SPM_amp;;SPM_amp;;SPM_amp;hlinetabularcenter{table}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img30.gif">'; 
$key = q/{figure}vspace15cmlabelhc2temp{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img71.gif">'; 
$key = q/{figure}centervskip9.cmlabelmr{figure}/;
$cached_env_img{$key} ='<IMG  ALIGN=BOTTOM ALT="" SRC="img126.gif">'; 

1;

